apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lk0n4dgrn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lk0n4dgrn-nodejs 
  name: lk0n4dgrn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lk0n4dgrn-nodejs 
